POST http://localhost:3000/api/entries/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbmlzYW5jaGV6LmRldkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRXZDgvRDRTT0JRckdnZU1tWEJHLjkuVEwuZGpqTmJObEFkbUJMcjNBOGVhMkVvbS5FTktEcSIsImlhdCI6MTY1NDkwMzk5OX0.ruF1UIUwIVtpBDBe1r06GFBdSXIgTGG1_nsDzDSwRpU

{
  "field1": "Wally is here",
  "field2": 17
}

// Before testing use log in endpoint to get a new token.
// Expect a 201 with the content of the new entry including the field "user" with the user id.
